### ISSUE TITLE
Transfocator in 8-ID-D & 8-ID-E

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/bluesky#61]
### move

![image](https://github.com/user-attachments/assets/be73ecb8-4039-4582-8eca-313ed265931b)

### lenses

![image](https://github.com/user-attachments/assets/2d8b415f-22a2-4751-b9f9-b3f42397b980)

**Comment by prjemian** [comment]
See [transfocator support at APS-POLAR](https://github.com/APS-4ID-POLAR/polar_instrument/pull/7).

**Comment by prjemian** [comment]
Need the structure & PVs of the CRL in E station

**Comment by sureshnaps** [comment]
Pete,
Here is the structure of CRLs.

CRL-1 which is in 8-ID-D and used by 8-ID-E and 8-ID-I:
There are 4 overall motion for the whole device. Not looking at the screen, sending from home.

8iddSoft:TRANS:m{1,2,3,4}
These are X, Y, pitch, yaw (need to check the sequence using the name fields). All closed loop with absolute encoders.
10 lenses: m{5,6,….,14}. These are all open loop stepper motor stages and the mode of operation is to drive from limit to limit. Negative limit is in the beam, Positive limit is out of the beam. We have to be careful that it does not stop somewhere in the middle.

CRL-2 which is in 8-ID-E after the Huber and used only by 8-ID-I:
8iddSoft:TRANS:m{25,26,27,28}
These are X, Y, pitch, yaw (need to check the sequence using the name fields). All closed loop with absolute encoders.
10 lenses: m{15,16,….,24}. These are all open loop stepper motor stages and the mode of operation is to drive from limit to limit. Negative limit is in the beam, Positive limit is out of the beam. We have to be careful that it does not stop somewhere in the middle.

PS: There will be a optics database from Xianbo that is being added as a pyDevice by Max which will add logic like filters with these 10 filters to give 2^10 options. ETA of this testing is in 2 weeks.

Suresh





From: Pete R Jemian ***@***.***>
Date: Wednesday, August 28, 2024 at 4:55 PM
To: aps-8id-dys/bluesky ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [aps-8id-dys/bluesky] Transfocator in 8-ID-D & 8-ID-E (Issue #61)
Need the structure & PVs of the CRL in E station — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread. Message ID: <aps-8id-dys/bluesky/issues/61/2316314489@ github. com>
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

Need the structure & PVs of the CRL in E station
